%\VignetteIndexEntry{Differential expression analysis of RNA-seq data with the "HTSDiff" package}
%\VignettePackage{HTSDiff}

% To compile this document
% library('cacheSweave');rm(list=ls());Sweave('HTSDiff.Rnw',driver=cacheSweaveDriver());system("pdflatex HTSDiff")

\documentclass[10pt,oneside]{article}
\usepackage{natbib}

\newcommand{\thetitle}{Differential expression analysis of RNA-seq data with the HTSDiff package}
\usepackage{whbiocvignette}

\title{\textsf{\textbf{\thetitle}}}
\author{S. Balzergue, G. Rigaill, V. Brunaud, E. Blondet, A. Rau$^1$, O. Rogier, J. Caius, \\
C. Maugis-Rabusseau,
L. Soubigou-Taconnat, S. Aubourg, C. Lurin, E. Delannoy, \\
and M.-L. Martin-Magniette.\\[1em]
\texttt{$^1$andrea.rau@jouy.inra.fr}}

% The following command makes use of SVN's 'Date' keyword substitution
% To activate this, I used: svn propset svn:keywords Date HTSCluster.Rnw
\date{\Rpackage{HTSDiff} version \Sexpr{packageDescription("HTSDiff")$Version}}

\SweaveOpts{keep.source=TRUE,eps=FALSE,pdf=FALSE,png=TRUE,include=FALSE,width=5.4,height=3.7,resolution=180}

\begin{document}
<<options,results=hide,echo=FALSE>>=
options(digits=3, width=100)
@

\maketitle

\begin{abstract}
This vignette explains the use of the \Rpackage{HTSDiff} package. 
For a presentation of the statistical method, please see our paper.
\end{abstract}

\tableofcontents

%--------------------------------------------------
\section{Input data} \label{sec:prep}
%--------------------------------------------------

In this vignette, we will work with the gene level read counts from
the \Rpackage{...} data package.

%------------------------------------------------------------
\section{Inference: Identifying differentially expressed genes} \label{sec:inference}
%------------------------------------------------------------
To be completed.

%\clearpage
%------------------------------------------------------------
\section{Further reading}\label{sec:further}
%------------------------------------------------------------

For more information on the statistical method, see \citep{Rau2014} and \citep{Balzergue2014} .

\section{Session Info}
<<sessi>>=
sessionInfo()
@

\bibliographystyle{unsrt}
\bibliography{HTSDiff}


\end{document}
